services:
  db:
    image: postgres
    ports:
      - 54329:5432
    restart: always
    environment:
      POSTGRES_DB: nest
      POSTRGRES_USER: root
      POSTGRES_PASSWORD: root
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
